# Generated by Django 5.0 on 2023-12-23 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacto', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contacto',
            old_name='nombre_apellido',
            new_name='nombre_Apellido',
        ),
    ]
