# Generated by Django 5.0 on 2023-12-23 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_post_autor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='categoria',
            new_name='categoría',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='titulo',
            new_name='título',
        ),
        migrations.RemoveField(
            model_name='post',
            name='subtitulo',
        ),
        migrations.AddField(
            model_name='post',
            name='subtítulo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
